### ISSUE TITLE
Remove draper dependency

### ISSUE THREAD

**Issue by vyper** [guru-pr/gurupr#102]

**Comment by kpearson** [comment]
On it. :-)

**Comment by kpearson** [comment]
I need a little clarification. What exactly do you want done here?

I see the TODO regarding pointing the Draper dependency at the official Draper repo. Is this what done?

**Comment by vyper** [comment]
In others projects I saw a bad performance in decorators using draper. So, I think that remove draper is a good point and we have few decorators... (:

In weekend I updated to official repo, but I was only updating oldest gems.

**Comment by vyper** [comment]
Thanks @yez and @kpearson! (;
