### ISSUE TITLE
Error on edit event

### ISSUE THREAD

**Issue by vyper** [guru-pr/gurupr#11]
When I list event, field `occurred_at` is correct...

![screen shot 2015-02-20 at 1 06 35 pm](https://cloud.githubusercontent.com/assets/22549/6288618/57eca430-b901-11e4-87f2-136040f497e1.png)

But when I open form to edit, value of `occurred_at` is wrong...

![screen shot 2015-02-20 at 1 07 35 pm](https://cloud.githubusercontent.com/assets/22549/6288635/7c262df8-b901-11e4-83ae-30a9fba1ea63.png)

**Comment by fabiosammy** [comment]
But:
* "2015-03-04 22:00:00" is "2015-03-04 19:00:00 -0300" (TIMEZONE)

**Comment by lccezinha** [comment]
What about use datetimepicker in this field ? http://eonasdan.github.io/bootstrap-datetimepicker/

**Comment by vyper** [comment]
It's cool! Awesome!
