### ISSUE TITLE
What about Rubocop?

### ISSUE THREAD

**Issue by brunoocasali** [guru-pr/gurupr#142]
Will be nice if we implement the rules of rubocop into this project...

What do you think?!

**Comment by vyper** [comment]
Why not use [CodeClimate](https://codeclimate.com/features)?

**Comment by brunoocasali** [comment]
@vyper yeah!! I will provide a PR implementing the rubocop rules. You can integrate with codeclimate, or if you want I can do it too...

**Comment by vyper** [comment]
Ok @brunoocasali! (:

I never used this feature of codeclimate. 😅

**Comment by brunoocasali** [comment]
It's really cool, I'm working to improve the code quality of this project https://github.com/julianguyen/ifme and there we use this feature, you can see it in action if you want... ;)

**Comment by vyper** [comment]
Cool! Let's go! (:
