### ISSUE TITLE
SSH with Let's Encrypt

### ISSUE THREAD

**Issue by brunoocasali** [guru-pr/gurupr#148]
We can use free SSH by https://letsencrypt.org/ to make https://gurupr.org/ :)

**Comment by vyper** [comment]
I tried... But, for enable this addon in heroku we have to pay... ):

Do you know a way without payment @brunoocasali? 😬

**Comment by brunoocasali** [comment]
@vyper I've implemented for free SSH in sites i've made with heroku, I know is not the full solution but at least will appear in url the https! I do that basically following this video https://www.youtube.com/watch?v=ILeg3c5GJ8M what do you think?

**Comment by vyper** [comment]
Maybe is an option? https://github.com/KMarshland/heroku-ssl/blob/master/README.md

**Comment by vyper** [comment]
I tried to use [sabayon] (https://github.com/dmathieu/sabayon) and worked! But I could not force redirected to use https. ):

**Comment by vyper** [comment]
I upgraded app to hobby and I used ssl by heroku.
I'll try contact heroku to him support us enabling "free" for our app. hehe

**Comment by brunoocasali** [comment]
@vyper if you agree, u could send me the credentials and then I try to add https with cloudflare ;)
