### ISSUE TITLE
Upgrade factory girl to factory bot

### ISSUE THREAD

**Issue by vyper** [guru-pr/gurupr#208]
https://github.com/thoughtbot/factory_bot/blob/v4.9.0/UPGRADE_FROM_FACTORY_GIRL.md

**Comment by Atul9** [comment]
I would like to contribute to this. I tried to update the gem but on bundle install I get --
```
Your bundle is locked to route_translator (5.5.2), but that version could not be found in any of the sources listed your Gemfile. If you haven't changed sources, that means the author of route_translator (5.5.2) has removed it. You'll
need to update your bundle to a different version of route_translator (5.5.2) that hasn't been removed in order to
install
```

**Comment by vyper** [comment]
Probally version 5.5.2 had an error and was marked as "unavailable". Maybe the best option are upgrade to [5.5.3] (https://github.com/enriclluelles/route_translator/blob/master/CHANGELOG.md#553--2018-01-12). (:

**Comment by vyper** [comment]
@Atul9

I fixed the [deppbot branch](https://github.com/guru-pr/gurupr/pull/212) and the gems are fine now! (:

**Comment by vinhnd2010** [comment]
So could you please close this issue, @vyper? :)

**Comment by vyper** [comment]
@vinhnd2010 I fixed error on route_translator, factory_girl need upgrade yet. (:

**Comment by tae8838** [comment]
@vyper I've made a PR for this issue :)

**Comment by vyper** [comment]
Thanks @tae8838! (:
