### ISSUE TITLE
Layout improvements

### ISSUE THREAD

**Issue by jnettome** [guru-pr/gurupr#25]
I think that isn't the main goal right now, but I took some interface (and feature) references for us.

- http://www.brug.be
- http://www.atlrug.com (nice logo, presentations)
- http://nwrug.org
- http://utruby.org (features)
- http://lrug.org
- http://berlin.onruby.de
- http://vanruby.org

Share your thoughts!

**Comment by vyper** [comment]
I really like the layout of BRUG. 

Also I did tests on the app to use on GURU-PR, but the app need many improvements. :disappointed:

So, I decided wrote from zero. :smiley:

**Comment by adilsoncarvalho** [comment]
Indeed BRUG is the nicest one. It uses a wider use of space. I agree on the great logo of the atlrug as @jnettome pointed out.

This makes me remind of Kiko's offer of a logo for us, @vyper. I still think that something remindind of an _araucária_ would be great and quite paranaense.

I'll submit a PR with some css hacks for the layout.

Other thing I loved was this effect while loading the member's photos on http://berlin.onruby.de/

![screen shot 2015-07-03 at 11 25 48](https://cloud.githubusercontent.com/assets/349796/8500936/33f8aa18-2177-11e5-9501-90b14eb1a4b1.png)

**Comment by nandomoreirame** [comment]
Hi guys!
I made a sketch here with the simple css..

what we all think of the idea? I can continue when yours approve ;)

## Home
![guru-pr-home](https://cloud.githubusercontent.com/assets/1318271/11971770/7728ec28-a929-11e5-897c-6864c02d7159.png)

## Events
![guru-pr-events](https://cloud.githubusercontent.com/assets/1318271/11971772/7cf44828-a929-11e5-950e-baaa6194b19a.png)

thanks

**Comment by vyper** [comment]
@nandomoreirame is **very beautiful** for me! (:

**Comment by vyper** [comment]
"tacale pau marco véio"

**Comment by vyper** [comment]
Thanks @nandomoreirame! (:

You did an awesome work!
