### ISSUE TITLE
Fix fields for form (on admin) that don't align with container border

### ISSUE THREAD

**Issue by vyper** [guru-pr/gurupr#30]
![image](https://cloud.githubusercontent.com/assets/22549/6508596/8b6f8a5c-c338-11e4-926e-3f84a9c3f5da.png)

**Comment by adilsoncarvalho** [comment]
Is this still a thing? It looks correct to me (I'm using Chrome/Mac). Just took this shots from the production site.

![screen shot 2015-07-03 at 11 38 03](https://cloud.githubusercontent.com/assets/349796/8501024/16a25558-2178-11e5-8fbf-aaf3f7c682bb.png)

![image](https://cloud.githubusercontent.com/assets/349796/8501045/3f56cc36-2178-11e5-9efa-48337ee2e959.png)

**Comment by vyper** [comment]
Resolved in #84. Thanks @nandomoreirame, again! 😂
