### ISSUE TITLE
Newsletter

### ISSUE THREAD

**Issue by vyper** [guru-pr/gurupr#63]
We need a newsletter to sent mail directly to our users. I think the [sendgrid](http://sendgrid.com/) is a good choice.

It is necessary three tasks to integrate with mailchimp.

**Comment by adilsoncarvalho** [comment]
:+1: for Mailchimp as it is free for our needs and it has a very complete [API](https://apidocs.mailchimp.com/)

Its API would allow us to mechanise warnings for our events while still allowing us to send _human made_ newsletters.

It also have several gems available including some official, like this [one](https://bitbucket.org/mailchimp/mailchimp-api-ruby/)

**Comment by vyper** [comment]
Changed from mandrill to sendgrid, now mandrill [is paid](https://mandrill.zendesk.com/hc/en-us/articles/217467117).
