### ISSUE TITLE
Added twitter messages on site

### ISSUE THREAD

**Issue by vyper** [guru-pr/gurupr#80]

**Comment by neves** [comment]
You mean filtered by hashtag? If so, which one?

**Comment by vyper** [comment]
HEHE, I put ideas here and forget from the others people. d:

We have a twitter: https://twitter.com/guru_pr

We can get last messages and put in home... what do you think?

**Comment by neves** [comment]
What about this:
https://twitter.com/settings/widgets/new
Fast, clean and unobtrusive.

Em seg, 28 de set de 2015 às 11:58, Leonardo Saraiva <
notifications@github.com> escreveu:

**Comment by vyper** [comment]
Remains only the big question... we choose the better option/location to show the twitter timeline in layout.... (:

**Comment by neves** [comment]
Generate the widget code on a new branch so we can play with it.
Put it above the members list for now.

Em seg, 28 de set de 2015 às 14:19, Leonardo Saraiva <
notifications@github.com> escreveu:
